# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a7934749106204a010304855dd3405ff818985cdfd210218fc51bae570906946b95dccec59872bb012c0a789cbe55fda6bffa0f3c05dd6c74f690a7d486d39

test:
  secret_key_base: c817a38f5157b281e3d1e93df992f9cea95cb6b2d758242380151d1758819fbd240bcf8b4a2f089e1856648a82e0f7a7e9d50082e484b0c6eaf57a71c159dfe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
