export const nameToTag = {
  "52 Wk Hi":["52_week_high","Highest stock price over the past 52 Week period","52weekhighlow"],
  "52 Wk Lo":["52_week_low","Lowest stock price over the past 52 week period","52weekhighlow"],
  "Acquisitions":["acquisitions","USD, Total acqusitions on balance sheet","acqusition"],
  "Daily Volume (avg)":["average_daily_volume","Average number of shares traded","averagedailytradingvolume"],
  "Altman Z-Score":["altmanzscore","Bankruptcy risk indicator (Below 2 at risk)","altman"],
  "Asset Turnover":["assetturnover","Ratio of Sales to Total Assets","assetturnover"],
  "Beta":["beta","Volatility of stock price relative to market","beta"],
  "Book Value/Share":["bookvaluepershare","Net value of assets on balance sheet","bookvalue"],
  "Cash Flow Financing":["netcashfromfinancingactivities","Net cash from issuing stock/debt or paying dividends, etc","cashflowfromfinancing"],
  "Cash Flow Investing":["netcashfrominvestingactivities","Net cash from investment activity such as plant & equiptment","cashflowfinvestingactivities"],
  "Cash Flow Operating":["netcashfromoperatingactivities","Net cash from regular business activities such as selling goods","cash-flow-from-operating-activities"],
  "Chief Executive Officer":["ceo","Key member of team in charge of decisions","ceo"],
  "Company Name":["name","Name of company","firm"],
  "Current Ratio":["currentratio","Ratio that measures firm's ability to pay debt obligations","currentratio"],
  "Days to Cover":["days_to_cover","Number of days to close short positions","daystocover"],
  "Debt to Equity":["debttoebitda","Measure of a company's ability to pay off debt","debt_ebitda"],
  "Dividend per Share":["dividend","Distribution of a portion of company's earnings paid to shareholders","dividend"],
  "Dividend Yield":["dividendyield","Dividend payment relative to company's share price","dividendyield"],
  "EBITDA Growth":["ebitdagrowth","Growth of Earnings Before Interest, Taxes, Depreciation, and Amortization","ebitda"],
  "EBITDA Margin":["ebitdamargin","EBITDA as a percentage of company's total revenue","ebitdamargin"],
  "Employees":["employees","Number of firm employees","employee-engagement"],
  "Enterprise Value":["enterprisevalue","Market cap plus debt, miniority interest and preferred shares minus cash","enterprisevalue"],
  "EPS":["basiceps","Earnings per Share","eps"],
  "EPS Growth":["epsgrowth","Growth of Earnings per Shares","eps"],
  "Gross Margin":["grossmargin","Firm's sales relative to its cost of goods sold","grossmargin"],
  "Goodwill":["goodwill","Intangible assets on balance sheet","goodwill"],
  "Inventory Turnover":["invturnover","Measure of firm's efficiency in turning over inventory","inventoryturnover"],
  "Leverage Ratio":["leverageratio","Measure of firms capital mix (Debt/Equity)","leverageratio"],
  "Long-Term Debt":["longtermdebt","Financial obligations lasting over one year","longtermdebt"],
  "Interest Expense":["longtermdebtinterestexpense","Cost incurred by an entity for borrowed funds","interestexpense"],
  "Long-Term Debt/EBITDA":["ltdebttoebitda","Long-term debt divided by operating profit","debt_ebitda"],
  "Market Cap":["marketcap","Total shares outstanding times current stock price","marketcapitalization"],
  "Net Income":["profitmargin","Company's total earnings (or profit)","netincome"],
  "Net Income Growth":["netincomegrowth","Growth in company's profit","netincome"],
  "Operating Margin":["operatingmargin","Measure of company's operating efficiency","operatingmargin"],
  "Price/Book":["pricetobook","Book value relative to shares price","price-to-bookratio"],
  "Price/Earnings":["pricetoearnings","Earnings relative to share price","price-earningsratio"],
  "Price/Sales":["pricetorevenue","Annual Sales to share price","price-to-salesratio"],
  "Price/Fwd Earnings":["pricetonextyearearnings","Forecasted earnings relative to current share price","forwardpe"],
  "Price/Fwd Sales":["pricetonextyearrevenue","Forecasted sales relative to current share price","price-to-salesratio"],
  "Quick Ratio":["quickratio","Measure of most liquid assets relative to short-term debt","quickratio"],
  "R&D Expense":["rdexpense","Any expenses associate with research and development of a company's goods & services","research-and-development-expenses"],
  "R&D to Revenue":["rdextorevenue","R&D expense relative to sales","research-and-development-expenses"],
  "Return on Assets":["roa","Earnings before interest and taxes relative to firms total assets","return_on_total_assets"],
  "Return on Equity":["roe","Net income relative to total equity on balance sheet","returnonequity"],
  "Return on Invested Capital":["roic","Company's efficiency at allocating the capital under its control to profitable investments","returnoninvestmentcapital"],
  "Revenue Growth":["revenuegrowth","Sales growth year over year","revenue"],
  "SG&A Expense":["sgaexpense","Direct and indirect selling expenses and general and administrative expenses of a company","sga"],
  "Short Interest":["short_interest","Quantity of stock shares that investors have sold short but not yet closed out","shortinterest"],
  "Total Assets":["totalassets","Total assets as reported on the balance sheet","asset"],
  "Total Gross Profit":["totalgrossprofit","Total revenue minus cost of goods sold","grossprofit"],
  "Total Operating Expenses":["totaloperatingexpenses","Expenses incurred through normal business activity","operating_expense"],
  "Total Operating Income":["totaloperatingincome","Total profit gross of interest, taxes, depreciation and amortization","operatingearnings"],
  "Total Revenue":["totalrevenue","Total firm sales over the year","revenue"]}
